#!/bin/bash

# if [ ! -f .Renviron ]; then
#   echo -e "CONDA_DIR=${CONDA_DIR}\nR_LIBS_USER=/srv/r" >> .Renviron
# fi

# See https://jira-secure.berkeley.edu/browse/DH-305
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
export XDG_CONFIG_HOME=${REPO_DIR}/rstudio-config
exec "$@"
